apiVersion: v1
kind: Service
metadata:
  name: hello-k8s
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: hello-k8s
  type: {{ .Values.service.type }}