namespace:
  name: staging

service:
  port: 5000

image:
  tag: '3.0'
  pullPolicy: Always

replicaCount: 3

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits:
    cpu: 500m
    memory: 128Mi
